### ISSUE TITLE
Move to JuliaSIMD?

### ISSUE THREAD

**Issue by ranocha** [JuliaSIMD/StrideArrays.jl#46]
All other repositories of the ecosystem seem to live there (https://github.com/JuliaSIMD/). Thus, moving it might increase the visibility of this nice package

**Comment by chriselrod** [comment]
Yeah, I can move it.

**Comment by chriselrod** [comment]
https://github.com/JuliaSIMD/StrideArrays.jl
https://github.com/JuliaRegistries/General/pull/56349
