### ISSUE TITLE
Bounds checking

### ISSUE THREAD

**Issue by MasonProtter** [JuliaSIMD/StrideArrays.jl#80]
How do we feel about turning on bounds checks like normal arrays for StrideArrays? If you're writing good code, bounds checks should often be elided, and if people really want they can always use `@inbounds`. The fact that the only way to turn on bounds checks is by redefining a function makes it so that packages like Bumper.jl who depend on StrideArrays can't provide bounds checks by default.

**Comment by chriselrod** [comment]
Yeah, it's fine. 
Base doesn't use `@inbounds` because "maybe people implemented their array types wrong".

There was some benchmark I wanted to win without reimplementing a bunch of base methods, but I don't care about those benchmarks anymore.

**Comment by chriselrod** [comment]
BTW, I have aliased Julia so that I get `--check-bounds=yes` by default, so I was probably less impacted by this than most people.
